---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "portal-mkmp"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "odoo-server"
  namespace: "portal-mkmp"
  labels:
    app: "odoo-server"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "odoo-server"
  template:
    metadata:
      labels:
        app: "odoo-server"
    spec:
      containers:
      - name: "docker-1"
        image: "gcr.io/protean-pager-289712/github.com/indi90/docker:$SHORT_SHA"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "odoo-server-hpa-bywa"
  namespace: "portal-mkmp"
  labels:
    app: "odoo-server"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "odoo-server"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
